/**
 * sync-version.mjs
 *
 * Single version source: package.json -> version + versionSuffix
 *
 * Syncs version (semver) into:
 *   - src-tauri/tauri.conf.json  (drives getVersion() at runtime)
 *   - src-tauri/Cargo.toml       (Rust package version)
 *   - src/lib/buildInfo.ts       (generated; exposes suffix to the React app)
 *   - ../README.md               (version badge)
 *
 * Usage:
 *   node scripts/sync-version.mjs                  # sync only
 *   node scripts/sync-version.mjs 0.3.0            # new version, keep suffix
 *   node scripts/sync-version.mjs 0.3.0 beta       # new version + new suffix
 *   node scripts/sync-version.mjs 0.3.0 ""         # stable release (no suffix)
 *
 * Badge color scheme (auto-selected from suffix):
 *   alpha        ->  red          (unstable, breaking changes expected)
 *   beta         ->  orange       (feature-complete but still rough)
 *   rc           ->  yellow       (release candidate, nearly stable)
 *   (no suffix)  ->  brightgreen  (stable release)
 *   other        ->  blue         (custom / informational)
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const root    = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = resolve(root, '..');

// -- Paths --------------------------------------------------------------
const PKG_JSON    = resolve(root, 'package.json');
const TAURI_CONF  = resolve(root, 'src-tauri', 'tauri.conf.json');
const CARGO_TOML  = resolve(root, 'src-tauri', 'Cargo.toml');
const BUILD_INFO  = resolve(root, 'src', 'lib', 'buildInfo.ts');
const README      = resolve(repoRoot, 'README.md');

// -- Read package.json -------------------------------------------------
const pkg = JSON.parse(readFileSync(PKG_JSON, 'utf8'));

// -- Apply CLI args if provided: [version] [suffix] --------------------
const [,, argVersion, argSuffix] = process.argv;

if (argVersion) pkg.version = argVersion;
// argSuffix of "" means "remove suffix" — only update if explicitly passed
if (argSuffix !== undefined) pkg.versionSuffix = argSuffix;

const version = pkg.version;
const suffix  = pkg.versionSuffix ?? '';   // e.g. "alpha", "beta", ""
const full    = suffix ? `${version}-${suffix}` : version;

if (!version) {
  console.error('Could not read version from package.json');
  process.exit(1);
}

// Write back to package.json (captures any CLI changes)
writeFileSync(PKG_JSON, JSON.stringify(pkg, null, 2) + '\n');
console.log(`package.json     ->  ${full}`);

// -- Sync tauri.conf.json (semver only — no suffix, getVersion() requirement) --
const tauriConf = JSON.parse(readFileSync(TAURI_CONF, 'utf8'));
if (tauriConf.package.version !== version) {
  tauriConf.package.version = version;
  writeFileSync(TAURI_CONF, JSON.stringify(tauriConf, null, 2) + '\n');
  console.log(`tauri.conf.json  ->  ${version}`);
} else {
  console.log(`tauri.conf.json  already ${version}`);
}

// -- Sync Cargo.toml ----------------------------------------------------
let cargo = readFileSync(CARGO_TOML, 'utf8');
const cargoVersionRe = /^(version\s*=\s*)"[^"]*"/m;
const match = cargo.match(cargoVersionRe);

if (!match) {
  console.error('Could not find version field in Cargo.toml');
  process.exit(1);
}

const currentCargo = match[0].match(/"([^"]*)"/)[1];
if (currentCargo !== version) {
  cargo = cargo.replace(cargoVersionRe, `$1"${version}"`);
  writeFileSync(CARGO_TOML, cargo);
  console.log(`Cargo.toml       ->  ${version}`);
} else {
  console.log(`Cargo.toml       already ${version}`);
}

// -- Write src/lib/buildInfo.ts (generated — exposes suffix to the app) -
const buildInfoContent =
`// AUTO-GENERATED by scripts/sync-version.mjs — do not edit manually.
export const VERSION_SUFFIX = '${suffix}';
`;
writeFileSync(BUILD_INFO, buildInfoContent);
console.log(`buildInfo.ts     ->  suffix="${suffix}"`);

// -- Update README.md version badge -------------------------------------
const BADGE_COLORS = { alpha: 'red', beta: 'orange', rc: 'yellow', '': 'brightgreen' };
const badgeColor = BADGE_COLORS[suffix] ?? 'blue';

let readme = readFileSync(README, 'utf8');
// shields.io encodes "-" as "--" in badge URLs
const badgeVersion = full.replace(/-/g, '--');
const badgeRe = /!\[Version\]\(https:\/\/img\.shields\.io\/badge\/version-[^)]+\)/;
const newBadge = `![Version](https://img.shields.io/badge/version-${badgeVersion}-${badgeColor}.svg)`;
if (badgeRe.test(readme)) {
  const updated = readme.replace(badgeRe, newBadge);
  if (updated !== readme) {
    writeFileSync(README, updated);
    console.log(`README.md badge  ->  ${full} (${badgeColor})`);
  } else {
    console.log(`README.md badge  already ${full}`);
  }
} else {
  console.warn('README.md: version badge not found — skipping.');
}

console.log(`\nAll files are at v${full}.`);
